[package]
name = "order_matcher"
version = "0.1.0"
edition = "2021"

[dependencies]
im = "15.1.0"
itertools = "0.10.2"
nom = "7.1.1"
futures = "0.3.21"
async-std = {version = "1.9.0", features = ["attributes"]}
actix-rt = "*"
